py.install_sources(
     '_cidr_address.py',
     '_cidr_clean.py',
     '_cidr_compact.py',
     '_cidr_nets.py',
     '_cidr_range.py',
     '_cidr_range_split.py',
     '_cidr_sort.py',
     '_cidr_split_type.py',
     '_cidr_subnet.py',
     'cidr_types.py',
     '_cidr_valid.py',
     '__init__.py',
     'ip_version.py',
     '_rfc_1918.py',
  subdir: 'py_cidr/_network'
)
