#!/usr/bin/bash
#
# Source code checks
#
# Run in top level after build/install to build/pkg
# 
# Requires
# - pylint
# - pycodestyle
# - mypy

dest=$(realpath "./src/py_cidr")
export PYTHONPATH="$dest"

echo "---------------------"
echo "==> pylint"
pylint --max-line-length=110 "$dest"/*.py "$dest"/*/*.py

echo "---------------------"
echo "==> pycodestyle"
pycodestyle --max-line-length=110 "$dest"/*.py "$dest"/*/*.py

echo "---------------------"
echo "==> mypy"
opts=(--check-untyped-defs --follow-untyped-imports --show-error-context --pretty)
mypy   "${opts[@]}" "$dest"

echo "---------------------"
echo "Checking tests"

pylint --max-line-length=110 src/tests/*.py
pycodestyle --max-line-length=110 src/tests/*.py
mypy "${opts[@]}" src/tests/


