#!/bin/bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2024-present  Gene C <arch@sapience.com>
#
# installer script for py-cidr
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c
#
dest="$1"
self='py-cidr'
mod='py_ccidr'

info="Docs README.rst scripts packaging"
infodir="/usr/share/${self}"

license="Docs/License/License.rst"
licensedir="/usr/share/licenses/${self}"

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
fi

# make app link in /usr/bin
apps=('py-cidr-cache-print')

sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")
installdir="${dest}${sitedir}"

uv_opts=(
    --python /usr/bin/python
    --system
    --no-build-isolation
    --link-mode=copy
    --compile-bytecode
)

# shared
/usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}
/usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/

/usr/bin/uv pip install ${uv_opts[@]} --target "$installdir" dist/*.whl
/usr/bin/rm -rf "$installdir"/.lock

# copied from src dir
if [ -v apps ] ; then
    /usr/bin/mkdir -p "${dest}/usr/bin"
    for app in ${apps[@]}
    do
        /usr/bin/rsync -av src/${app}.py ${dest}/usr/bin/${app} 
    done
fi
exit 0
